// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_WEB_API_KEY'] ?? 'AIzaSyC-Yz4CuOjQ97VFIxOWoIMqr1WI5COdY6w',
        appId: '1:608360411758:web:c3fd18dc69eab4baef6c7f',
        messagingSenderId: '608360411758',
        projectId: 'notesync-saaddev',
        authDomain: 'notesync-saaddev.firebaseapp.com',
        storageBucket: 'notesync-saaddev.firebasestorage.app',
        measurementId: 'G-X4HGRTT3KX',
      );

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY'] ?? 'AIzaSyDczCF_mpQLOSDkMrae_UaccLfL9TJLfp4',
        appId: '1:608360411758:android:e5aa26551f053883ef6c7f',
        messagingSenderId: '608360411758',
        projectId: 'notesync-saaddev',
        storageBucket: 'notesync-saaddev.firebasestorage.app',
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_IOS_API_KEY'] ?? 'AIzaSyCWqt4J_ZCVwPzZlI4QiP1pEgl2yGrchUs',
        appId: '1:608360411758:ios:45e12f4ea90461d1ef6c7f',
        messagingSenderId: '608360411758',
        projectId: 'notesync-saaddev',
        storageBucket: 'notesync-saaddev.firebasestorage.app',
        iosBundleId: 'com.notesync.notesync',
      );

  static FirebaseOptions get macos => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_IOS_API_KEY'] ?? 'AIzaSyCWqt4J_ZCVwPzZlI4QiP1pEgl2yGrchUs',
        appId: '1:608360411758:ios:45e12f4ea90461d1ef6c7f',
        messagingSenderId: '608360411758',
        projectId: 'notesync-saaddev',
        storageBucket: 'notesync-saaddev.firebasestorage.app',
        iosBundleId: 'com.notesync.notesync',
      );

  static FirebaseOptions get windows => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_WEB_API_KEY'] ?? 'AIzaSyC-Yz4CuOjQ97VFIxOWoIMqr1WI5COdY6w',
        appId: '1:608360411758:web:8d3a0e93983e8f15ef6c7f',
        messagingSenderId: '608360411758',
        projectId: 'notesync-saaddev',
        authDomain: 'notesync-saaddev.firebaseapp.com',
        storageBucket: 'notesync-saaddev.firebasestorage.app',
        measurementId: 'G-ZYT0QVTZ00',
      );
}
